### ISSUE TITLE
Misleading bringup documentation

### ISSUE THREAD

**Issue by bananen-republik** [tux-evse/iso15118-simulator-rs#1]
Hello everybody,

in your bringup video you are showing how to start the simulator. I tried it the same way, with using "./afb-evcc/etc/binding-start-evcc.sh" but it always leads me to:
"/home/admin/iso15118-simulator-rs
Warning: To active tls support, PKI_TLS_DIR must be define (-p|--pki_tls_sim_dir)
Fail: The scenario  file must be define (-f|--scenario_file)
Usage:
        -h|--help        displays this text
        -d|--debug       run the script in debug mode
        -i|--iface       specify the network interface (default:"evcc-veth" or from env var IFACE_SIMU)
        -c|--scenario_uid        specify the scenario uid (default:"evcc" or from env var SCENARIO_UID)
        -f|--scenario_file
        -s|--simulation          specify the simulator mode (default:"injector" or from env var SIMULATION_MODE)
        -m|--simulation_conf     specify the simulator conf
                                        (default:"/etc/default//binding-simu15118-evcc.yaml" if tls support
                                         or     :"/etc/default//binding-simu15118-evcc-no-tls.yaml" if no tls support
                                         or from env var SIMULATION_CONF)
        -p|--pki_tls_sim_dir     specify *.pem files directory (_client_chain.pem,_client_key.pem,_contract_chain.pem,_contract_key.pem)
        admin@TUX-EVSE:~/iso15118-simulator-rs$ ./afb-evcc/etc/binding-start-evcc.sh -i enp0s3 -s
"

Even if i specify the interface it shows me the help page.
What am I doing wrong? What configurations do i need to set?

**Comment by ronan22** [comment]
The script binding-start-evcc has been improve and some information has been add to the README file.
You can update your package or use it from the source

@bananen-republik can you confirm you have a good configuration now?

**Comment by fulup-bzh** [comment]
Documentation was updated by Ronan. As we did not get any feedback, we expect the issue to be solved. Would you have more concern, feel free to open a new request.
