### ISSUE TITLE
can't load binding

### ISSUE THREAD

**Issue by bananen-republik** [tux-evse/iso15118-simulator-rs#2]
Hello everybody,

I still getting issues while trying to start the simulator.
The output is:
`NOTICE: Browser URL= http://localhost:1234 NOTICE: Serving rootdir=. uploaddir=. ERROR: binding [/usr/redpesk/iso15118-simulator-rs/lib/libafb_sim15118_evcc.so] not loadable: libiso15118.so.1.0: cannot open shared object file: No such file or directory [./src/libafb/apis/afb-api-so.c:81,load_binding] ERROR: can't load binding /usr/redpesk/iso15118-simulator-rs/lib/libafb_sim15118_evcc.so [./src/main-afb-binder.c:241,load_one_binding_cb]`

and my starting command: `./afb-evcc/etc/binding-start-evcc.sh -c evcc -f /etc/default/tesla-3-din.json`
I tried to update the repdesk dependencies but it didn't helped.

What am i doing wrong?

Best regards

**Comment by jobol** [comment]
did answer https://github.com/redpesk-core/afb-binder/issues/1 help?

**Comment by bananen-republik** [comment]
@jobol sorry, i opened the issue in the wrong repository.
I'm still trying to apply your solution but for now it didn't helped.

**Comment by jobol** [comment]
So as I wrote, the program afb-binder really doesn't find libiso15118.so.1.0. I can't help more in finding why.

**Comment by fulup-bzh** [comment]
From the error, it looks like afb-binder does not find the low level is15118 encoding sharelib that should be provided by iso15118-encoders package. This package is a dependency of iso15118-simulator-rs and should be installed automatically in /usr/lib64/libiso15118.so.1.0, I also surprise by the .SO search path.

What distribution are you using ? Are you using a mix of binary and source package ?  ./afb-evcc/etc/binding-start-evcc.sh  is the name of command from git source and not the command to use with binary package.

Using Quick-Start instruction from https://github.com/tux-evse/iso15118-simulator-rs/blob/main/README.md#quick-start-simulating-both-evseevcc should work out of the box. If it does not please let known your distribution and @ronan22 will investigate.

**Comment by bananen-republik** [comment]
Hi @fulup-bzh I followed the quick-start guide and ended with the same error.
I'm using Ubuntu24.04 amd64 distribution in a virtualizized environment.

I can see the libiso15118.so.1.0 in /usr/lib64/ and i verified that the user has got permissions on that library.

**Comment by jobol** [comment]
What is the result of the command 

```
ldd /usr/redpesk/iso15118-simulator-rs/lib/libafb_sim15118_evcc.so
```

**Comment by bananen-republik** [comment]
`
admin@TUX-EVSE:~/iso15118-simulator-rs$ ldd /usr/redpesk/iso15118-simulator-rs/lib/libafb_sim15118_evcc.so
        linux-vdso.so.1 (0x00007ffe8b31b000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007010f8dd8000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007010f8a00000)
        /lib64/ld-linux-x86-64.so.2 (0x00007010f8f87000)
        libiso15118.so.1.0 => not found
        libgnutls.so.30 => /lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007010f8806000)
        libp11-kit.so.0 => /lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007010f8c34000)
        libidn2.so.0 => /lib/x86_64-linux-gnu/libidn2.so.0 (0x00007010f87e4000)
        libunistring.so.5 => /lib/x86_64-linux-gnu/libunistring.so.5 (0x00007010f8637000)
        libtasn1.so.6 => /lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007010f8c1c000)
        libnettle.so.8 => /lib/x86_64-linux-gnu/libnettle.so.8 (0x00007010f85e2000)
        libhogweed.so.6 => /lib/x86_64-linux-gnu/libhogweed.so.6 (0x00007010f859a000)
        libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x00007010f8516000)
        libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x00007010f850a000)
`

**Comment by jobol** [comment]
There is probably an issue with the path of the library.
Can you add /usr/lib64 to your LD_LIBRARY_PATH? As below:

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64
```

And retry (1) ldd comand above, checking the lib is found (2) running the script that  fails

**Comment by fulup-bzh** [comment]
@ronan22 could you check where you install sharelib on Ubuntu. By default unlike Opensuse or Fedora they do not use /usr/lib64

**Comment by BenMuthigAixACCT** [comment]
I ran into the same issue (also using Ubuntu 24.04).
Running `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64` and then retrying `ldd /usr/redpesk/iso15118-simulator-rs/lib/libafb_sim15118_evcc.so`
yields
linux-vdso.so.1 (0x00007ffcadfeb000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x0000700f48a3c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x0000700f48800000)
	/lib64/ld-linux-x86-64.so.2 (0x0000700f48beb000)
	libiso15118.so.1.0 => /usr/lib64/libiso15118.so.1.0 (0x0000700f4871b000)
	libgnutls.so.30 => /lib/x86_64-linux-gnu/libgnutls.so.30 (0x0000700f48521000)
	libp11-kit.so.0 => /lib/x86_64-linux-gnu/libp11-kit.so.0 (0x0000700f4837d000)
	libidn2.so.0 => /lib/x86_64-linux-gnu/libidn2.so.0 (0x0000700f48a18000)
	libunistring.so.5 => /lib/x86_64-linux-gnu/libunistring.so.5 (0x0000700f481d0000)
	libtasn1.so.6 => /lib/x86_64-linux-gnu/libtasn1.so.6 (0x0000700f481ba000)
	libnettle.so.8 => /lib/x86_64-linux-gnu/libnettle.so.8 (0x0000700f48165000)
	libhogweed.so.6 => /lib/x86_64-linux-gnu/libhogweed.so.6 (0x0000700f4811d000)
	libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x0000700f48099000)
	libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x0000700f4808d000)

I also ran `binding-start-evcc --pki_tls_sim_dir ./temp/ --scenario_file /etc/default/tesla-3-din.json` again and it seems to work.

Thank you for your help.
Ben

**Comment by fulup-bzh** [comment]
Good news. I ask @ronan22 to fix the error on Ubuntu binary package. He is also reworking the OCI container, but as I said this will take a little more time.

**Comment by fulup-bzh** [comment]
If you have any more issue please open a new bug.
